# Generated by Django 3.2.16 on 2022-11-27 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vessel',
            old_name='received_time',
            new_name='received_time_utc',
        ),
    ]
